name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the entire repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install dependencies (inside the microservice folder)
      - name: Install dependencies
        working-directory: microservice
        run: npm ci

      # 4) Run tests
      - name: Run Jest tests
        working-directory: microservice
        run: npm test

      # 5) Upload test results (if you configure jest-junit)
      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: microservice/jest-results

      # 6) Upload coverage folder
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: microservice/coverage
