name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List built files
        run: ls -R dist || echo "No dist directory found"

      - name: Archive build output
        uses: actions/upload-artifact@v3.1.3
        if: success() && hashFiles('dist/**') != ''
        with:
          name: build-artifact
          path: |
            dist
