name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    # Using ubuntu-latest as the runner for compatibility with most Node.js projects and tools.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure package-lock.json is up-to-date
        run: |
          npm install --package-lock-only

      - name: Install dependencies
        run: npm ci
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          npm test
          mkdir -p coverage && echo "Ensure coverage directory exists"

      - name: Archive coverage (if any)
        if: success() && (hashFiles('coverage/**') != '' || hashFiles('jest-results.json') != '')
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-results
          path: |
            coverage
            jest-results.json
            jest-results.json


