
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Archive coverage (if any)
        if: success() && (hashFiles('coverage/**') != '' || hashFiles('jest-results.json') != '')
        - uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage/
            jest-results.json
